import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Porta Prêmiada',
  description: 'Project Generated by create next app'
};

export default function DoorsLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
